package:
    name: renode
    version: {{GIT_DESCRIBE_TAG}}

source:
    git_url: https://github.com/renode/renode.git
    git_rev: master
    patches:
        - use_conda_cc.patch       [not win]
        - lower_mono_version.patch [not win]

build:
    missing_dso_whitelist:
        # This library comes with .NET
        - "$SYSROOT/System32/mscoree.dll" [win]

requirements:
    build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - git
        - python 2.7.*   [not win]
        - python         [win]
        - automake       [not win]
        - autoconf       [not win]
        - libtool        [not win]
        - mono           [not win]
        - gtk2           [not win]
        - vc >=10        [win]
    run:
        - python 2.7.*   [not win]
        - python         [win]
        - glib           [not win]
        - mono           [not win]
        - gtk2           [not win]
        - pcre           [not win]
        - cairo          [not win]
        - pango          [not win]
        - atk            [not win]
        - fontconfig     [not win]
        - robotframework 3.1
        - netifaces
        - requests
        - psutil
        - pyyaml

test:
    commands:
        - renode --help

about:
    home: https://github.com/renode/renode
    license: The MIT License (MIT)
    license_file: LICENSE
